name: Tests

on:
  [push]

jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install Test Dependencies
      run: pip3 install -r requirements.txt
    
    - name: Run Tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: pytest
    
    
