name: Tests

on:
  [push]

jobs:
  test:
  
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install Test Dependencies
      run: pip install -r requirements.txt
    
    - name: Run Tests
      run: pytest
    
    
